realty/realty/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('realtyapp.urls', namespace='realtyapp')),
    path('user/', include('userapp.urls', namespace='userapp'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

realty/realtyapp/urls.py
from realtyapp import views
from django.urls import path

app_name = 'realtyapp'

urlpatterns = [
    # path('', views.main_view, name='index'),
    path('', views.IndexListView.as_view(), name='index'),
    # path('sale/', views.sale, name='sale'),
    path('sale/', views.SaleListView.as_view(), name='sale'),
    # path('rent/', views.rent, name='rent'),
    path('rent/', views.RentListView.as_view(), name='rent'),
    # path('new_buildings/', views.new_buildings, name='new_buildings'),
    path('new_buildings/', views.New_buildingsListView.as_view(), name='new_buildings'),
    # path('message/', views.message, name='message'),
    path('message/', views.MessageCreateView.as_view(), name='message'),
    # path('apartment/<int:id>/', views.apartment, name='apartment'),
    path('apartment/<int:pk>/', views.ApartmentDetailView.as_view(), name='apartment'),
    # path('personal_area/', views.personal_area, name='pers_area'),
    path('personal_area/', views.PersonalListView.as_view(), name='pers_area'),
    path('create_apart/', views.ApartmentCreateFormView.as_view(), name='create_apart'),
    path('updata_apart/<int:pk>/', views.ApartmentUpdataView.as_view(), name='updata_apart'),
    path('delete_confirm/<int:pk>/', views.ApartmentDeleteView.as_view(), name='delete_apart'),
    path('delete_image_confirm/<int:pk>', views.ImageDeleteView.as_view(), name='delete_image')
]

realty/realtyapp/forms.py
from django import forms
from .models import Message_user, Apartment, Category, Metro, Area_city, \
    Balcony, Room_count, Material, Sity, Currency

class MessageForm(forms.ModelForm):
    name = forms.CharField(label='Имя',
                           widget=forms.TextInput(attrs={'placeholder': 'Name', 'class': 'form-control'}))
    message = forms.CharField(label='Сообщение',
                              widget=forms.TextInput(attrs={'placeholder': 'Message', 'class': 'form-control'}))
    telefone = forms.CharField(label='Телефон', required=False,
                               widget=forms.TextInput(attrs={'placeholder': 'Telefone', 'class': 'form-control'}))
    email = forms.EmailField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    class Meta:
        model = Message_user
        fields = '__all__'



GEEKS_CHOICES_METRO = (('', ''),
                 ('Площадь Тукая', 'Площадь Тукая'),
                 ('Дубравная', 'Дубравная'),
                 ('Проспект Победы', 'Проспект Победы'),
                 ('Северный вокзал', 'Северный вокзал'),
                 ('Суконная слобода', 'Суконная слобода'),
                 ('Аметьево', 'Аметьево'),
                 ('Горки', 'Горки'),
                 ('Авиастроительная', 'Авиастроительная'),
                  ('1Козья слобода', 'Козья слобода'),
                 ('Яшьлек', 'Яшьлек'),
                       ('Кремлёвская', 'Кремлёвская'))
GEEKS_CHOICES_AREA = (('', ''),
                      ('Кировский', 'Кировский'),
                      ('Вахитовский', 'Вахитовский'),
                      ('Ново-Савиновский', 'Ново-Савиновский'),
                      ('Московский', 'Московский'),
                      ('Приволжский', 'Приволжский'),
                      ('Советский', 'Советский'),
                      ('Авиастроительный', 'Авиастроительный'))
GEEKS_CHOICES_CATEGORY = (('Продажа', 'Продажа'),
                          ('Аренда', 'Аренда'))

class ApartmentForm(forms.Form):
    metro_name = forms.ChoiceField(label='Метро', required=False, choices=GEEKS_CHOICES_METRO,
                                   widget=forms.Select(attrs={'class': 'form-control'}))

    floor_number = forms.CharField(label='Этаж',
                              widget=forms.TextInput(attrs={'placeholder': 'этаж', 'class': 'form-control'}))
    metro_distance = forms.CharField(label='Путь до метро', required=False,
                              widget=forms.TextInput(attrs={'placeholder': 'в мин. пешком', 'class': 'form-control'}))
    total_square = forms.CharField(label='Общая площадь',
                              widget=forms.TextInput(attrs={'placeholder': 'кв.м.', 'class': 'form-control'}))
    living_square = forms.CharField(label='Жилая площадь', required=False,
                              widget=forms.TextInput(attrs={'placeholder': 'кв.м.', 'class': 'form-control'}))
    floor_total = forms.CharField(label='Всего этажей',widget=forms.
                                  TextInput(attrs={'placeholder': 'количество этажей', 'class': 'form-control'}))

    count_room = forms.CharField(label='Комнат',
                                         widget=forms.TextInput(attrs={'class': 'form-control'}))
    material = forms.CharField(label='Материал',widget=forms.
                               TextInput(attrs={'placeholder': 'материал строения', 'class': 'form-control'}))

    balcony_type = forms.CharField(label='Тип балкона', required=False,
                                         widget=forms.TextInput(attrs={'placeholder': 'Балкон, Лоджия, их количество',
                                                                       'class': 'form-control'}))

    is_home_appliances = forms.CharField(label='Техника',widget=forms.
                                         TextInput(attrs={'placeholder': 'С техникой, какая, без техники', 'class': 'form-control'}))

    is_furniture = forms.CharField(label='Мебель', widget=forms.
                                   TextInput(attrs={'placeholder': 'С мебелью, какая, без мебели', 'class': 'form-control'}))
    cost = forms.CharField(label='Стоимость', widget=forms.
                               TextInput(attrs={'placeholder': 'в руб.', 'class': 'form-control'}))
    currency = forms.CharField(label='Валюта', initial='руб',widget=forms.TextInput(attrs={'class': 'form-control'}))

    house_number = forms.CharField(label='Дом', widget=forms.
                               TextInput(attrs={'placeholder': 'номер дома', 'class': 'form-control'}))
    street = forms.CharField(label='Улица', widget=forms.
                               TextInput(attrs={'placeholder': 'street', 'class': 'form-control'}))
    city = forms.CharField(label='Населенный пункт', initial='Казань', widget=forms.
                               TextInput(attrs={'class': 'form-control'}))

    area_city = forms.ChoiceField(label='Район', required=False, choices=GEEKS_CHOICES_AREA,
                                       widget=forms.Select(attrs={'class': 'form-control'}))
    advertising_object = forms.CharField(label='Краткая реклама', required=False, widget=forms.
                               TextInput(attrs={'class': 'form-control'}))
    description = forms.CharField(label='Описание объекта', widget=forms.
                               Textarea(attrs={'class': 'form-control'}))

    category = forms.ChoiceField(label='Тип объявления', choices=GEEKS_CHOICES_CATEGORY,
                                 widget=forms.Select(attrs={'class': 'form-control'}))

    images = forms.ImageField(label='Добавить фото', required=False)

realty/realtyapp/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect, redirect
from realtyapp.models import Apartment, Category, Images, Message_user, Street, Images_url, Metro, Room_count
from realtyapp.models import Material, Balcony, Currency, Sity, Area_city
from .forms import MessageForm, ApartmentForm
from django.urls import reverse, reverse_lazy
from django.core.mail import send_mail
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, FormView, View
from django.views.generic.edit import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin , UserPassesTestMixin


def check_object(model, name):
    objects_base = model.objects.all()
    for object_base in objects_base:
        if object_base.name == name:
            return object_base
    object_base = model.objects.create(name=name)
    return object_base

# def main_view(request):
#     return render(request, 'realtyapp/index.html', context={})

class IndexListView(ListView):
    template_name = 'realtyapp/index.html'

    def get_queryset(self):
        return

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data()
        context['title'] = 'сайт недвижимости'
        return context

# def sale(request):
#     id_category = Category.objects.get(name='sale')
#     sales = Apartment.objects.filter(category=id_category)
#     return render(request, 'realtyapp/sale.html', context={'sales': sales})

class SaleListView(ListView):
    model = Apartment
    template_name = 'realtyapp/sale.html'
    context_object_name = 'sales'
    paginate_by = 5

    def get_queryset(self):
        self.sales = Apartment.objects.select_related('metro_name', 'count_room', 'material', 'balcony_type',
                                                      'currency', 'street', 'city', 'area_city').\
            filter(category__name__in=['sale', 'Продажа'])
        return self.sales

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data()
        context['title'] = 'продажа квартир'
        context['sales_all'] = self.sales
        return context

# def rent(request):
#     id_category = Category.objects.get(name='rent')
#     rents = Apartment.objects.filter(category=id_category)
#     return render(request, 'realtyapp/rent.html', context={'rents': rents})

class RentListView(ListView):
    model = Apartment
    template_name = 'realtyapp/rent.html'
    context_object_name = 'rents'
    paginate_by = 5

    def get_queryset(self):
        self.rents = Apartment.objects.select_related('metro_name', 'count_room', 'material', 'balcony_type',
                                                      'currency', 'street', 'city', 'area_city').\
            filter(category__name__in=['rent', 'Аренда'])
        return self.rents

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data()
        context['title'] = 'аренда квартир'
        context['rents_all'] = self.rents
        return context

class New_buildingsListView(ListView):
    template_name = 'realtyapp/new_buildings.html'

    def get_queryset(self):
        return


# def new_buildings(request):
#     return render(request, 'realtyapp/new_buildings.html', context={})

# def message(request):
#     if request.method == 'GET':
#         message = MessageForm()
#         return render(request, 'realtyapp/message.html', context={'message': message})
#     else:
#         message = MessageForm(request.POST)
#         if message.is_valid():
#             name = message['name'].value()
#             email = message['email'].value()
#             text_message = message['message'].value()
#             # print(f'name  {name}')
#             # print(f'email  {email}')
#             # print(f'text_message  {text_message}')
#             message.save()
#
#             send_mail(
#                 'Response letter',
#                 f'{name} Ваше письмо получено {text_message}',
#                 '',
#                 [email],
#                 fail_silently=True,
#             )
#             return HttpResponseRedirect(reverse('realtyapp:index'))
#         else:
#             return render(request, 'realtyapp/message.html', context={'message': message})

class MessageCreateView(LoginRequiredMixin, CreateView):
    model = Message_user
    form_class = MessageForm
    success_url = reverse_lazy('realtyapp/index.html')
    template_name = 'realtyapp/message.html'

    def form_valid(self, form):
        # print(f'form  {form}')
        name = form['name'].value()
        email = form['email'].value()
        text_message = form['message'].value()
        # print(f'name  {name}')
        # print(f'email  {email}')
        # print(f'text_message  {text_message}')
        send_mail(
            'Response letter',
            f'{name} Ваше письмо получено {text_message}',
            '',
            [email],
            fail_silently=True,
        )
        return HttpResponseRedirect(reverse('realtyapp:index'))
# def apartment(request, id):
#     apartment = get_object_or_404(Apartment, id=id)
#     categorys = apartment.category.all()
#     for category in categorys:
#         name_category = category.name
#     images = Images.objects.filter(apartment=apartment)
#     return render(request, 'realtyapp/apartment.html', context={'apartment': apartment, 'images': images,
#                                                                 'name_category': name_category})

class ApartmentDetailView(DetailView):
    model = Apartment
    template_name = 'realtyapp/apartment.html'


    def get(self, request, *args, **kwargs):
        self.apartment_id = kwargs['pk']
        return super().get(request, *args, **kwargs)

    def get_object(self, queryset=None):
        apartment = Apartment.objects.select_related('metro_name', 'count_room', 'material', 'balcony_type',
                                                      'currency', 'street', 'city', 'area_city')\
                                                        .get(pk=self.apartment_id)
        self.images_url = apartment.get_apart_images_url
        self.images = apartment.get_apart_images
        self.categorys = apartment.category.all()

        # return get_object_or_404(Apartment, pk=apartment.pk)
        return apartment


    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['images_url'] = self.images_url
        context['categorys'] = self.categorys
        context['images'] = self.images
        return context


# def personal_area(request):
#     return render(request, 'realtyapp/personal_area.html', context={})

class PersonalListView(UserPassesTestMixin, ListView):
    model = Apartment
    success_url = reverse_lazy('realtyapp:index')
    template_name = 'realtyapp/personal_area.html'
    # paginate_by = 5

    def test_func(self):
        return self.request.user

    def get_queryset(self):
        apartments_user = Apartment.objects.select_related('metro_name', 'count_room', 'material',
                                                           'balcony_type','currency', 'street', 'city',
                                    'area_city').prefetch_related('category').filter(user=self.request.user).all()

        return apartments_user


class ApartmentCreateFormView(LoginRequiredMixin, FormView):
    form_class = ApartmentForm
    success_url = reverse_lazy('realtyapp:pers_area')
    template_name = 'realtyapp/create_apart.html'

    def form_valid(self, form):
        # print()
        # print(f'dir(form)  {dir(form)}')
        # print()
        # print(f'form.data  {form.data}')
        # print()
        # print(f'form.files  {form.files["images"]}')
        # print()
        metro = check_object(Metro, form.data['metro_name'])
        count_room = check_object(model=Room_count, name=form.data['count_room'])
        material = check_object(model=Material, name=form.data['material'])
        balcony_type = check_object(model=Balcony, name=form.data['balcony_type'])
        currency = check_object(model=Currency, name=form.data['currency'])
        street = check_object(model=Street, name=form.data['street'])
        city = check_object(model=Sity, name=form.data['city'])
        area_city = check_object(model=Area_city, name=form.data['area_city'])
        user = self.request.user
        category = check_object(model=Category, name=form.data['category'])

        imag = form.files.get('images', None)



        apartment = Apartment.objects.create(metro_name=metro, floor_number=form.data['floor_number'],
                                             metro_distance=form.data['metro_distance'], total_square=form.data['total_square'],
                                             living_square=form.data['living_square'], floor_total=form.data['floor_total'],
                                             count_room=count_room, material=material,
                                             balcony_type=balcony_type, is_home_appliances=form.data['is_home_appliances'],
                                             is_furniture=form.data['is_furniture'], cost=form.data['cost'],
                                             currency=currency, house_number=form.data['house_number'],
                                             street=street, city=city, area_city=area_city,
                                             advertising_object=form.data['advertising_object'], description=form.data['description'],
                                             user=user)
        if imag:
            image = Images.objects.create(image=imag, apartment=apartment)
        apartment.category.add(category)
        apartment.save()
        return super().form_valid(form)



class ApartmentUpdataView(UserPassesTestMixin, FormView):
    form_class = ApartmentForm
    success_url = reverse_lazy('realtyapp:pers_area')

realty/realtyapp/templates/realtyapp/delete_image_confirm.html
{% extends "base.html" %}

{% block title %}
  Фото удаление
{% endblock %}

{% block topic %}
    <h1>Удаление</h1>


{% endblock %}

{% block whattopic %}
    Фото
{% endblock %}

{% block content %}

 <img src="{{object.image.url}}">
<hr>
<hr>
<h2>Удалить это Фото ?</h2>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Да</button>
    </form>

{% endblock %}

realty/realtyapp/templates/realtyapp/message.html
{% extends "base.html" %}

{% block title %}
  Сообщение
{% endblock %}

{% block topic %}
  Свяжитесь
  с нами
{% endblock %}

{% block whattopic %}
  Есть вопросы? У нас есть ответы.
{% endblock %}

{% block content %}
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">

        <form method="post">
          {% csrf_token %}
          {{ message.as_p }}
          <br>
          <br>
          <div class="form-group">
            <button type="submit" class="btn btn-primary" id="sendMessageButton">Отправить</button>
          </div>
        </form>
      </div>
    </div>
{% endblock %}

realty/realtyapp/templates/realtyapp/personal_area.html
{% extends "base.html" %}

{% block title %}
  Личный кабинет
{% endblock %}

{% block topic %}
  Личный кабинет
{% endblock %}

{% block whattopic %}
    Ваши объявления
{% endblock %}

{% block content %}
    <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="btn btn-primary" href="{% url 'realtyapp:create_apart' %}">Создать объявление</a>
              <br>
              <hr>

          </li>

        <li class="list-inline text-center">
            <h2>Ваши объявления</h2>
        </li>
            {% with pers_list=object_list %}
               {% for ad in pers_list %}
    </ul>
        <a href="{% url 'realtyapp:apartment' pk=ad.pk %}">
                <p>{{ad.description}}</p>
                <p>{{ad.metro_name}}</p>
                <p>{{ad.floor_number}}</p>
                <p>{{ad.metro_distance}}</p>
                <p>{{ad.total_square}}</p>
                <p>{{ad.living_square}}</p>
                <p>{{ad.floor_total}}</p>
                <p>{{ad.count_room}}</p>
                <p>{{ad.material}}</p>
                <p>{{ad.balcony_type}}</p>
                    <p>{{ad.is_home_appliances}}</p>
                        <p>{{ad.is_furniture}}</p>
                            <p>{{ad.cost}}</p>
                                <p>{{ad.house_number}}</p>
                                    <p>{{ad.street}}</p>
                                        <p>{{ad.city}}</p>
        <p>{{ad.area_city}}</p>
        <p>{{ad.advertising_object}}</p>
            {% for categor in ad.category.all %}
            {{categor}}
            {% endfor %}
    </a>

    <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="btn btn-primary" href="{% url 'realtyapp:updata_apart' pk=ad.pk %}">Редактировать</a>
              <hr>
          </li>

        <li class="nav-item">
            <a class="btn btn-primary" href="{% url 'realtyapp:delete_apart' pk=ad.pk %}">Удалить</a>
            <hr>
          </li>


            {% endfor %}
        {% endwith %}
    </ul>



{% endblock %}

realty/realtyapp/templates/realtyapp/rent.html
{% extends "base.html" %}
{% load str_extensions %}

{% block title %}
  Аренда
{% endblock %}

{% block topic %}
  {{title|capitalize}}
{% endblock %}

{% block whattopic %}

{% endblock %}

{% block content %}
<h5>Всего найдено квартир:  {{rents_all|length}}</h5>
    <div class="row">

      <div class="col-lg-8 col-md-10 mx-auto">

        {% for item in rents %}
        <div class="post-preview">
          <a href="{% url 'realtyapp:apartment' pk=item.pk %}">
            <h2 class="post-title"></h2>
             <h3>{{ item.count_room.name }}-комн. квартира, {{ item.total_square }} м.кв.,</h3>
              <h3>{{ item.floor_number }}/{{ item.floor_total }} этаж</h3>
              <h3>{{ item.street.name }}, {{ item.house_number }}, {{ item.city.name }}</h3>
              <br>
              <h2>{{ item.cost }} {{ item.currency.name }}</h2>

            <h3 class="post-subtitle">
<!--              Problems look mighty small from 150 miles up-->
            </h3>
          </a>
<!--          <p class="post-meta">Posted by-->
<!--            <a href="#">Start Bootstrap</a>-->
<!--            on September 24, 2019</p>-->
        </div>
        <br>
        <hr>
        <br>
        {% endfor %}

  <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; На первую</a>
            <a href="?page={{ page_obj.previous_page_number }}">Предыдущая</a>
        {% endif %}

        <span class="current">
            <h5>Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.</h5>
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Следующая</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">На последнюю &raquo;</a>
        {% endif %}
    </span>
</div>
<!--        <div class="post-preview">-->
<!--          <a href="post.html">-->
<!--            <h2 class="post-title">-->
<!--              I believe every human has a finite number of heartbeats. I don't intend to waste any of mine.-->
<!--            </h2>-->
<!--          </a>-->
<!--          <p class="post-meta">Posted by-->
<!--            <a href="#">Start Bootstrap</a>-->
<!--            on September 18, 2019</p>-->
<!--        </div>-->
<!--        <hr>-->
<!--        <div class="post-preview">-->
<!--          <a href="post.html">-->
<!--            <h2 class="post-title">-->
<!--              Science has not yet mastered prophecy-->
<!--            </h2>-->
<!--            <h3 class="post-subtitle">-->
<!--              We predict too much for the next year and yet far too little for the next ten.-->
<!--            </h3>-->
<!--          </a>-->
<!--          <p class="post-meta">Posted by-->
<!--            <a href="#">Start Bootstrap</a>-->
<!--            on August 24, 2019</p>-->
<!--        </div>-->
<!--        <hr>-->
<!--        <div class="post-preview">-->
<!--          <a href="post.html">-->
<!--            <h2 class="post-title">-->
<!--              Failure is not an option-->
<!--            </h2>-->
<!--            <h3 class="post-subtitle">-->
<!--              Many say exploration is part of our destiny, but it’s actually our duty to future generations.-->
<!--            </h3>-->
<!--          </a>-->
<!--          <p class="post-meta">Posted by-->
<!--            <a href="#">Start Bootstrap</a>-->
<!--            on July 8, 2019</p>-->
<!--        </div>-->
<!--        <hr>-->

<!--         Pager-->
<!--        <div class="clearfix">-->
<!--          <a class="btn btn-primary float-right" href="#">Older Posts &rarr;</a>-->
<!--        </div>-->
      </div>
    </div>
{% endblock %}

realty/realtyapp/templates/realtyapp/sale.html
{% extends "base.html" %}

{% block title %}
  Продажа
{% endblock %}

{% block topic %}
  {{title|capfirst}}
{% endblock %}

{% block whattopic %}

{% endblock %}



{% block content %}
    <h5>Всего найдено квартир:  {{sales_all|length}}</h5>
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
    {% with sales_temp=sales %}
        {% for item in sales_temp %}
        <div class="post-preview">
          <a href="{% url 'realtyapp:apartment' pk=item.pk %}">
            <h2 class="post-title"></h2>
             <h3>{{ item.count_room.name }}-комн. квартира, {{ item.total_square }} м.кв.,</h3>
              <h3>{{ item.floor_number }}/{{ item.floor_total }} этаж</h3>
              <h3>{{ item.street.name }}, {{ item.house_number }}, {{ item.city.name }}</h3>
              <br>
              <h2>{{ item.cost }} {{ item.currency.name }}</h2>

            <h3 class="post-subtitle">
<!--              Problems look mighty small from 150 miles up-->
            </h3>
          </a>
<!--          <p class="post-meta">Posted by-->
<!--            <a href="#">Start Bootstrap</a>-->
<!--            on September 24, 2019</p>-->
        </div>

        <br>
        <hr>
        <br>
        {% endfor %}
      {% endwith %}

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; На первую</a>
            <a href="?page={{ page_obj.previous_page_number }}">Предыдущая</a>
        {% endif %}

        <span class="current">
            <h5>Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.</h5>
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Следующая</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">На последнюю &raquo;</a>
        {% endif %}
    </span>
</div>
<!--        <div class="post-preview">-->
<!--          <a href="post.html">-->
<!--            <h2 class="post-title">-->
<!--              I believe every human has a finite number of heartbeats. I don't intend to waste any of mine.-->
<!--            </h2>-->
<!--          </a>-->
<!--          <p class="post-meta">Posted by-->
<!--            <a href="#">Start Bootstrap</a>-->
<!--            on September 18, 2019</p>-->
<!--        </div>-->
<!--        <hr>-->
<!--        <div class="post-preview">-->
<!--          <a href="post.html">-->
<!--            <h2 class="post-title">-->
<!--              Science has not yet mastered prophecy-->
<!--            </h2>-->
<!--            <h3 class="post-subtitle">-->
<!--              We predict too much for the next year and yet far too little for the next ten.-->
<!--            </h3>-->
<!--          </a>-->
<!--          <p class="post-meta">Posted by-->
<!--            <a href="#">Start Bootstrap</a>-->
<!--            on August 24, 2019</p>-->
<!--        </div>-->
<!--        <hr>-->
<!--        <div class="post-preview">-->
<!--          <a href="post.html">-->
<!--            <h2 class="post-title">-->
<!--              Failure is not an option-->
<!--            </h2>-->
<!--            <h3 class="post-subtitle">-->
<!--              Many say exploration is part of our destiny, but it’s actually our duty to future generations.-->
<!--            </h3>-->
<!--          </a>-->
<!--          <p class="post-meta">Posted by-->
<!--            <a href="#">Start Bootstrap</a>-->
<!--            on July 8, 2019</p>-->
<!--        </div>-->
<!--        <hr>-->

        <!-- Pager -->
<!--        <div class="clearfix">-->
<!--          <a class="btn btn-primary float-right" href="#">Older Posts &rarr;</a>-->
<!--        </div>-->
      </div>
    </div>
{% endblock %}

realty/realtyapp/templates/realtyapp/updata_apart.html
{% extends "base.html" %}

{% block title %}
  Редактор
{% endblock %}

{% block topic %}
  Редактировать
{% endblock %}

{% block whattopic %}
  объявление
{% endblock %}

{% block content %}

 <div class="row">

    <div class="col-lg-8 col-md-10 mx-auto">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {# form.as_p #}

            {% for field in form %}
                <p>{{field.label}}</p>
                    {% for error in field.errors %}
                        {{error}}
                    {% endfor %}
                <p>{{field}}</p>

            {% endfor %}

                    <hr>

            <button type="submit" class="btn btn-primary">Сохранить</button>
        </form>

            <hr>
            {% if images %}
                    Ваши фотографии
                {% for imag in images %}

                    <img src="{{imag.image.url}}">
                    <a href="{% url 'realtyapp:delete_image' pk=imag.pk %}">
                        <p class="btn btn-danger">Удалить фото</p>
                        <hr>
                    </a>
                {% endfor %}
            {% endif %}
    </div>
</div>

{% endblock %}