realty/realty/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('realtyapp.urls', namespace='realtyapp')),
    path('user/', include('userapp.urls', namespace='userapp'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

realty/realtyapp/urls.py
from realtyapp import views
from django.urls import path

app_name = 'realtyapp'

urlpatterns = [
    # path('', views.main_view, name='index'),
    path('', views.IndexListView.as_view(), name='index'),
    # path('sale/', views.sale, name='sale'),
    path('sale/', views.SaleListView.as_view(), name='sale'),
    # path('rent/', views.rent, name='rent'),
    path('rent/', views.RentListView.as_view(), name='rent'),
    # path('new_buildings/', views.new_buildings, name='new_buildings'),
    path('new_buildings/', views.New_buildingsListView.as_view(), name='new_buildings'),
    # path('message/', views.message, name='message'),
    path('message/', views.MessageCreateView.as_view(), name='message'),
    # path('apartment/<int:id>/', views.apartment, name='apartment'),
    path('apartment/<int:pk>/', views.ApartmentDetailView.as_view(), name='apartment'),
    # path('personal_area/', views.personal_area, name='pers_area'),
    path('personal_area/', views.PersonalListView.as_view(), name='pers_area'),
    path('create_apart/', views.ApartmentCreateFormView.as_view(), name='create_apart'),
    path('updata_apart/<int:pk>/', views.ApartmentUpdataView.as_view(), name='updata_apart'),
    path('delete_confirm/<int:pk>/', views.ApartmentDeleteView.as_view(), name='delete_apart'),
    path('delete_image_confirm/<int:pk>', views.ImageDeleteView.as_view(), name='delete_image')
]

realty/userapp/urls.py
from userapp import views
from django.urls import path
from django.contrib.auth.views import LogoutView

app_name = 'userapp'

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.UserRegistrationsView.as_view(), name='register'),
    path('confirmat/<str:email>/', views.ConfirmationListView.as_view(), name='confirmat')

]

realty/templates/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>{% block title %}{% endblock %}</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

  <!-- Custom styles for this template -->
  <link href="{% static 'css/clean-blog.min.css' %}" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand" href="/">карта сайта</a>

<!--      <a class="post-title" href="index.html">глааная</a>-->
<!--      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">-->
<!--        Menu-->
<!--        <i class="fas fa-bars"></i>-->
<!--      </button>-->
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'realtyapp:index' %}">главная</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'realtyapp:sale' %}">продажа</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'realtyapp:rent' %}">аренда</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'realtyapp:new_buildings' %}">новостройки</a>
          </li>


          {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'realtyapp:pers_area' %}">Кабинет</a>
            </li>
            <li class="nav-item">
                  <a class="nav-link" href="{% url 'realtyapp:message' %}">сообщение</a>
                </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'userapp:logout' %}">Выход</a>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'userapp:login' %}">Вход</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'userapp:register' %}">Регистрация</a>
            </li>
          {% endif %}



        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Header -->
  <header class="masthead" style="background-image: url('img/home-bg.jpg')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>{% block topic %}{% endblock %}</h1>
            <span class="subheading">{% block whattopic %}{% endblock %}</span>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Main Content -->
  <div class="container">
    {% block content %}{% endblock %}
  </div>

  <hr>

  <!-- Footer -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
<!--          <ul class="list-inline text-center">-->
<!--            <li class="list-inline-item">-->
<!--              <a href="#">-->
<!--                <span class="fa-stack fa-lg">-->
<!--                  <i class="fas fa-circle fa-stack-2x"></i>-->
<!--                  <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>-->
<!--                </span>-->
<!--              </a>-->
<!--            </li>-->
<!--            <li class="list-inline-item">-->
<!--              <a href="#">-->
<!--                <span class="fa-stack fa-lg">-->
<!--                  <i class="fas fa-circle fa-stack-2x"></i>-->
<!--                  <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>-->
<!--                </span>-->
<!--              </a>-->
<!--            </li>-->
<!--            <li class="list-inline-item">-->
<!--              <a href="#">-->
<!--                <span class="fa-stack fa-lg">-->
<!--                  <i class="fas fa-circle fa-stack-2x"></i>-->
<!--                  <i class="fab fa-github fa-stack-1x fa-inverse"></i>-->
<!--                </span>-->
<!--              </a>-->
<!--            </li>-->
<!--          </ul>-->
          <h1 class="copyright text-muted">{{ext_menu}}</h1>
        </div>
      </div>
    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Custom scripts for this template -->
  <script src="{% static 'js/clean-blog.min.js' %}"></script>

</body>

</html>